# Generated by Django 5.2.7 on 2025-10-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches_book_catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photos/'),
        ),
    ]
