# Generated by Django 5.2.7 on 2025-10-23 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches_book_catalog', '0003_coach_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('citizenship', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='coach_photos/pending/')),
                ('club', models.CharField(max_length=20)),
                ('license', models.CharField(max_length=50)),
                ('preffered_formation', models.CharField(max_length=100)),
                ('average_term_as_coach', models.FloatField()),
                ('description', models.TextField()),
                ('rate_per_session', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
