# Generated by Django 5.2.7 on 2025-10-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches_book_catalog', '0003_coach_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan untuk sesi ini (opsional)', null=True),
        ),
    ]
