# Generated by Django 5.2.7 on 2025-10-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches_book_catalog', '0004_coachrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coachrequest',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
